# PS5 Vulkan - meson cross file for building Mesa (RADV) for the console.
# Copyright (C) 2026 Mihawk-99
# SPDX-License-Identifier: GPL-3.0-or-later

[binaries]
c = sdk / 'bin/prospero-clang'
cpp = sdk / 'bin/prospero-clang++'
ar = sdk / 'bin/prospero-ar'
strip = sdk / 'bin/prospero-strip'
pkg-config = sdk / 'bin/prospero-pkg-config'

[host_machine]
system = 'freebsd'
cpu_family = 'x86_64'
cpu = 'x86_64'
endian = 'little'

[built-in options]
default_library = 'static'
c_args = ['-Wno-error']
cpp_args = ['-Wno-error']

[properties]
needs_exe_wrapper = true
